# Generated by Django 5.1.4 on 2025-01-03 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_client_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routinetype',
            name='code',
            field=models.IntegerField(verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='routinetype',
            name='description',
            field=models.TextField(blank=True, max_length=255, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='routinetype',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
    ]
